# Site settings
author: Adela Tatum
title: Addy's Software Engineering Journey
header-img: img/home-bg.png
email: lunaaddy21@gmail.com
copyright_name: Adela Tatum
description: > # this means to ignore newlines until "baseurl:"
  This will be interesting!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: addycodes
github_username:  addyluna

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
